# Generated by Django 4.2.7 on 2023-11-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0003_customuser_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='subjects_taught',
        ),
        migrations.AddField(
            model_name='customuser',
            name='courses_taught',
            field=models.ManyToManyField(blank=True, related_name='course_teachers', to='courses.course'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
