# Generated by Django 4.2.7 on 2023-11-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_question_active_quiz_active_topic_active_quizattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assessment_criteria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
