# Generated by Django 4.2.7 on 2023-11-27 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_assessment_criteria_course_learning_outcomes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='assessment_criteria',
        ),
        migrations.CreateModel(
            name='AssessmentCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_criteria', to='courses.course')),
            ],
        ),
    ]
